[package]
name = "automint-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "21", features = ["testutils"] }
automint-accrual = { path = "../accrual", features = ["testutils"] }
automint-bot-nft = { path = "../bot_nft", features = ["testutils"] }
automint-marketplace = { path = "../marketplace", features = ["testutils"] }
automint-registry = { path = "../registry", features = ["testutils"] }
automint-token = { path = "../token", features = ["testutils"] }
